In [ ]:
from sklearn.datasets import load_digits

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = load_digits()

In [ ]:
data.DESCR.split('\n')

['.. _digits_dataset:',
 '',
 'Optical recognition of handwritten digits dataset',
 '--------------------------------------------------',
 '',
 '**Data Set Characteristics:**',
 '',
 '    :Number of Instances: 1797',
 '    :Number of Attributes: 64',
 '    :Attribute Information: 8x8 image of integer pixels in the range 0..16.',
 '    :Missing Attribute Values: None',
 "    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)",
 '    :Date: July; 1998',
 '',
 'This is a copy of the test set of the UCI ML hand-written digits datasets',
 'https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits',
 '',
 'The data set contains images of hand-written digits: 10 classes where',
 'each class refers to a digit.',
 '',
 'Preprocessing programs made available by NIST were used to extract',
 'normalized bitmaps of handwritten digits from a preprinted form. From a',
 'total of 43 people, 30 contributed to the training set and different 13',
 'to the test set. 32x32 bitmaps are

In [ ]:
features = data.data
target = data.target

features.shape,target.shape

((1797, 64), (1797,))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, target, train_size = 0.6, random_state = 3)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1078, 64)
(719, 64)
(1078,)
(719,)


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
my_model = LogisticRegression()

In [ ]:
my_model.fit(X_train,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [ ]:
preds = my_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
print(accuracy_score(y_test, preds))

0.9582753824756607


In [ ]:
print(confusion_matrix(y_test, preds))

[[74  0  0  0  1  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  2  1]
 [ 0  1 77  0  0  0  0  0  0  0]
 [ 0  0  2 66  0  0  0  0  1  0]
 [ 0  4  0  0 79  0  1  1  1  0]
 [ 0  1  0  0  1 60  0  0  0  2]
 [ 0  1  0  0  0  1 55  0  1  0]
 [ 0  0  0  1  0  0  0 73  2  0]
 [ 0  1  0  0  0  1  0  0 66  0]
 [ 0  0  0  0  1  1  0  0  1 67]]


In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=.95)

In [ ]:
pca.fit(X_train)

PCA(n_components=0.95)

In [ ]:
pca.explained_variance_ratio_.shape

(28,)

In [ ]:
X_train_transformed = pca.transform(X_train)
X_test_transformed = pca.transform(X_test)

In [ ]:
X_train_transformed.shape, X_test_transformed.shape

((1078, 28), (719, 28))

In [ ]:
X_train_transformed

array([[  8.31885532, -11.63536164,   1.93999083, ...,   2.08339976,
          0.26786773,   0.5689659 ],
       [  3.69591051,  22.68576943,  -5.66316747, ...,  -1.929915  ,
          1.49342247,   1.38145364],
       [  8.7400552 ,  -2.00460958,  12.21941747, ...,   1.45736396,
          2.52737771,   3.08132256],
       ...,
       [ -0.20762926,  20.34392093,  -2.0983895 , ...,  -0.49341011,
          1.36157447,   1.76297356],
       [ 19.78689345,  -6.56299576,  18.79910461, ...,   2.92800901,
         -0.75285657,  -4.43258141],
       [-12.92312023, -11.63513571,  14.44423877, ...,   0.66691936,
          1.75415311,   2.45758818]])

In [ ]:
my_model.fit(X_train_transformed,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [ ]:
preds = my_model.predict(X_test_transformed)

In [ ]:
print(accuracy_score(y_test, preds))

0.9485396383866481


In [ ]:
import xgboost

In [ ]:
xgboost = xgboost.XGBRegressor()

In [ ]:
xgboost.fit(X_train_transformed,y_train)

XGBRegressor(base_score=0.5, booster=None, colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints=None,
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=0, num_parallel_tree=1,
             objective='reg:squarederror', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
             validate_parameters=False, verbosity=None)

In [ ]:
X_test[0].shape

(64,)

In [ ]:
pca.fit(X_test)

PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
pca.transform(X_test)[0].shape

(28,)

In [ ]:
my_model.fit(X_train_transformed,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
preds = my_model.predict(X_test_transformed)

In [ ]:
print(accuracy_score(y_test, preds))

0.9346314325452016


In [ ]:
print(confusion_matrix(y_test, preds))

[[74  0  0  0  1  0  0  0  0  0]
 [ 0 70  0  2  0  0  3  0  0  0]
 [ 0  1 76  1  0  0  0  0  0  0]
 [ 0  0  5 64  0  0  0  0  0  0]
 [ 1  4  0  0 78  0  1  1  1  0]
 [ 0  1  0  1  1 57  0  1  0  3]
 [ 1  1  0  0  0  1 54  0  1  0]
 [ 0  0  0  1  1  0  0 73  1  0]
 [ 0  3  0  0  0  1  0  1 62  1]
 [ 1  2  0  0  1  1  0  0  1 64]]
